# Generated by Django 5.1.3 on 2024-12-01 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='description',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='description',
        ),
        migrations.DeleteModel(
            name='BookmarkArchive',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
